spring:
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/database?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tlsdPcks05@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  ssl:
    keyAlias: spring
    key-store-password: '123456'
    key-store: keystore.p12
    keyStoreType: PKCS12
  port: 8443

